# Generated by Django 4.2.4 on 2024-06-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='restaurante',
            field=models.BooleanField(default=False),
        ),
    ]
